const media = {
  photo: [
    "bone",
    "crucifix burned",
    "dead body",
    "dirty water",
    "EMF reading",
    "fingerprint, any",
    "fingerprint, obake",
    "footprint",
    "freezing temperatures",
    "ghost",
    "ghost, D.O.T.S. ",
    "ghost, shadow",
    "ghost, translucent",
    "haunted mirror",
    "mist form",
    "monkey paw",
    "music box",
    "object levitating",
    "ouija board",
    "summoning circle",
    "tarot cards",
    "voodoo doll",
    "writing",
  ],
  video: [
    "crucifix burned",
    "crucifix aflame in Sunny Meadows chapel",
    "dead body",
    "door moved",
    "fire extinguished",
    "ghost",
    "ghost, hunting",
    "ghost, D.O.T.S.",
    "ghost, shadow",
    "ghost, shapeshift",
    "ghost, translucent",
    "interaction",
    "light flickering",
    "light exploded",
    "light switched",
    "mist form",
    "motion sensed",
    "music, distorted",
    "object thrown",
    "orbs",
    "ouija board",
    "rocking chair",
    "salt, disturbed",
    "writing",
  ],
  sound: [
    "crucifix burned",
    "EMF 5 reading",
    "fire extinguished",
    "ghost event",
    "ghost, hunting",
    "mist form",
    "music, distorted",
    "music box",
    "ouija board",
    "paranormal breathing",
    "paranormal groaning",
    "paranormal laughing",
    "paranormal scream",
    "paranormal talking",
    "paranormal whisper",
    "spirit box response",
    "toy, possessed",
    "writing",
  ],
};

export default media;
